import type { Metadata } from "next";
import { ABeeZee, Merriweather, Fira_Code, Playfair_Display } from "next/font/google";
import "./globals.css";
import { SavedItemsProvider } from "@/hooks/use-saved-items";

const fontSans = ABeeZee({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400",
});

const fontSerif = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
        <SavedItemsProvider>
            {children}
        </SavedItemsProvider>
      </body>
    </html>
  );
}